version: '3.8'

services:
  web:
    build:
      context: .
    image: django-base-api  # Specify the image name
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: django_db
    ports:
      - "5432:5432"
